name: NeyCustomMessages
version: '1.0.6-HotFix'
main: com.ney.messages.NeyCustomMessages
api-version: '1.13'
author: Ney
description: Custom messages for join, quit, death and announcements
commands:
  ncm:
    description: Reload the plugin configuration
    usage: /<command> reload